### ISSUE TITLE
Possible 'emacs-ipython-notebook' interaction problem?

### ISSUE THREAD

**Issue by dotmilk** [yitzchak/common-lisp-jupyter#45]
In the notebook in browser, I get results from running a cell. However in emacs, with the 'emacs-ipython-notebook' the websocket [here](https://github.com/millejoh/emacs-ipython-notebook/blob/0e6877cdc25a7a739b1f7299871950fbf18da928/lisp/ein-websocket.el#L106) is reporting an error of `(json-end-of-file)` after running the cell. Uncertain if this is due to jupyter / this kernel / ein or some mix there in. 

It doesn't seem to be ein, as it handles IHaskell fine. Is there a place I should look in this kernel to see why it is obviously giving the output to jupyter in the browser but a websocket from emacs is not getting the same info?

**Comment by yitzchak** [comment]
Unfortunately I have absolutely no experience with emacs let alone with emacs-ipython-notebook. It sounds like a JSON encoding error on either the EIN or the common-lisp-jupyter side. 

The argument the IHaskell works fine therefore EIN must not be the source of the error isn't really conclusive since common-lisp-jupyter works in Jupyter Notebooks, Jupyter Lab and it passes the kernel tests published by the Jupyter people.

I suspect that I'll have to setup EMACS and try it out to trace down the issue, until then can you give me a minimal example? Does it fail evaluating `nil`?

**Comment by dotmilk** [comment]
Minimal example would be `nil`, one attempt at executing a cell with only `nil` fails with:

`ein: [info] WS action [(json-end-of-file)] on-message (ws://127.0.0.1:8888/api/kernels/dfab0125-b53b-43cd-baff-c491e54660b2/channels?session_id=7c13390a-d129-4454-abe2-1f9f436d08ae) [5 times]`

 It might be that his JSON parser is being more strict or something. I will look into that as well. I did just notice the `[5 times]` bit, being uncertain about how these things communicate, does this indicate that jupyter sent 5 objects? Or was is this possible an ein internal thing, in that since it had an error ein asked the service to send it 4 more times in hopes of a better reply?

**Comment by dickmao** [comment]
Issues related to "emacs-ipython-notebook" should not be filed here.
