### ISSUE TITLE
Sort list of matches for code completion?

### ISSUE THREAD

**Issue by robert-dodier** [yitzchak/common-lisp-jupyter#56]
Hi, thanks a lot for your continued efforts on this project. I am working with the version of common-lisp-jupyter currently in Quicklisp, I think it is dated 2020-09-25 or something. The code completion feature works as expected (I'm working with Maxima via maxima-jupyter) and the only thing I have to add is that maybe it would help to sort the list of matches for display. It looks like the list is unsorted, from what I can tell.

Maxima-jupyter calls MATCH-SET-ADD to add a match item to the set of matches. I guess I am assuming that it's appropriate for the match set machinery to handle sorting the list, although maybe it should be the caller's responsibility.

Hope this helps in some way, and all the best.
Robert Dodier

**Comment by yitzchak** [comment]
The list was sorted originally, but I removed the sort because it appears that the Jupyter front end doesn't honor that sort when it removes duplicates from the set. I thought that they were doing their own sort at the same time, but it appears that they are not. So the only solution appears to be to add the local sort and accept the fact that the Jupyter front end may jack it up somewhat.

Cheers!

**Comment by yitzchak** [comment]
Fixed by 3b930615991879c05c30caa0a8b111711cb602fc

Thanks again Robert!
